language: node_js

node_js:
  - 10
  - 12

notifications:
  email: false

cache:
  yarn: true
  directories:
    - '.eslintcache'
    - 'node_modules'

git:
  depth: 5

script:
  - yarn ci

notifications:
  email: false
